#!/usr/bin/env python3
"""
CSV Analysis Tools for Evaluation Results

This module provides tools for analyzing CSV files generated by evaluation runs.
It includes statistical analysis, visualization support, and result comparison capabilities.

Usage:
    python -m src.backend.tools.csv_analysis_tools --input measurements.csv --analysis full
    python -m src.backend.tools.csv_analysis_tools --compare run1.csv run2.csv --output comparison.json
"""

import argparse
import csv
import json
import logging
import statistics
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class AnalysisResult:
    """Container for analysis results."""
    filename: str
    total_measurements: int
    successful_measurements: int
    failed_measurements: int
    success_rate_percent: float

    # Error metrics
    mean_absolute_error: Optional[float]
    median_absolute_error: Optional[float]
    std_absolute_error: Optional[float]
    mean_relative_error: Optional[float]
    root_mean_square_error: Optional[float]

    # Category breakdown
    category_stats: Dict[str, Dict[str, float]]

    # Processing performance
    mean_processing_time_ms: float
    total_processing_time_ms: float

    # Additional metadata
    timestamp: str
    analysis_version: str = "1.0"


class CSVAnalyzer:
    """Analyzer for evaluation CSV files."""

    def __init__(self):
        self.logger = logging.getLogger(__name__)

    def analyze_csv(self, csv_path: str, analysis_type: str = "full") -> AnalysisResult:
        """Analyze a CSV file and return structured results."""
        if not Path(csv_path).exists():
            raise FileNotFoundError(f"CSV file not found: {csv_path}")

        logger.info(f"Analyzing CSV file: {csv_path}")

        # Read CSV data
        df = pd.read_csv(csv_path)

        # Clean data
        df = self._clean_dataframe(df)

        # Perform analysis based on type
        if analysis_type == "basic":
            return self._basic_analysis(df, csv_path)
        elif analysis_type == "category":
            return self._category_analysis(df, csv_path)
        elif analysis_type == "performance":
            return self._performance_analysis(df, csv_path)
        else:  # full analysis
            return self._full_analysis(df, csv_path)

    def _clean_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        """Clean and prepare dataframe for analysis."""
        # Convert string numbers to float where appropriate
        numeric_columns = [
            'expected_volume_ml', 'measured_volume_ml', 'measured_diameter_mm',
            'measured_height_mm', 'confidence_percent', 'absolute_error_ml',
            'relative_error_percent', 'processing_time_ms'
        ]

        for col in numeric_columns:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        # Convert success to boolean
        if 'success' in df.columns:
            df['success'] = df['success'].astype(bool)

        return df

    def _basic_analysis(self, df: pd.DataFrame, filename: str) -> AnalysisResult:
        """Perform basic statistical analysis."""
        successful = df[df['success'] == True]
        failed = df[df['success'] == False]

        # Basic metrics
        abs_errors = successful['absolute_error_ml'].dropna()
        rel_errors = successful['relative_error_percent'].dropna()

        result = AnalysisResult(
            filename=Path(filename).name,
            total_measurements=len(df),
            successful_measurements=len(successful),
            failed_measurements=len(failed),
            success_rate_percent=len(successful) / len(df) * 100 if len(df) > 0 else 0,

            mean_absolute_error=abs_errors.mean() if not abs_errors.empty else None,
            median_absolute_error=abs_errors.median() if not abs_errors.empty else None,
            std_absolute_error=abs_errors.std() if not abs_errors.empty else None,
            mean_relative_error=rel_errors.mean() if not rel_errors.empty else None,
            root_mean_square_error=np.sqrt((abs_errors ** 2).mean()) if not abs_errors.empty else None,

            category_stats={},

            mean_processing_time_ms=df['processing_time_ms'].mean(),
            total_processing_time_ms=df['processing_time_ms'].sum(),

            timestamp=pd.Timestamp.now().isoformat()
        )

        return result

    def _category_analysis(self, df: pd.DataFrame, filename: str) -> AnalysisResult:
        """Perform category-focused analysis."""
        result = self._basic_analysis(df, filename)

        # Category breakdown
        category_stats = {}
        for category in df['category'].unique():
            if pd.isna(category):
                continue

            cat_data = df[df['category'] == category]
            cat_successful = cat_data[cat_data['success'] == True]
            cat_errors = cat_successful['absolute_error_ml'].dropna()

            category_stats[category] = {
                'total_images': len(cat_data),
                'successful_measurements': len(cat_successful),
                'success_rate_percent': len(cat_successful) / len(cat_data) * 100 if len(cat_data) > 0 else 0,
                'mean_absolute_error': cat_errors.mean() if not cat_errors.empty else None,
                'median_absolute_error': cat_errors.median() if not cat_errors.empty else None,
                'mean_processing_time_ms': cat_data['processing_time_ms'].mean()
            }

        result.category_stats = category_stats
        return result

    def _performance_analysis(self, df: pd.DataFrame, filename: str) -> AnalysisResult:
        """Perform performance-focused analysis."""
        result = self._basic_analysis(df, filename)

        # Add performance-specific metrics
        processing_times = df['processing_time_ms'].dropna()

        result.mean_processing_time_ms = processing_times.mean()
        result.total_processing_time_ms = processing_times.sum()

        # Add processing time distribution
        if 'category_stats' not in result.category_stats:
            result.category_stats = {}

        result.category_stats['processing_stats'] = {
            'min_time_ms': processing_times.min(),
            'max_time_ms': processing_times.max(),
            'median_time_ms': processing_times.median(),
            'percentile_95_ms': processing_times.quantile(0.95),
            'percentile_99_ms': processing_times.quantile(0.99)
        }

        return result

    def _full_analysis(self, df: pd.DataFrame, filename: str) -> AnalysisResult:
        """Perform comprehensive analysis."""
        result = self._category_analysis(df, filename)

        # Add all performance metrics
        performance_result = self._performance_analysis(df, filename)
        result.mean_processing_time_ms = performance_result.mean_processing_time_ms
        result.total_processing_time_ms = performance_result.total_processing_time_ms

        # Merge category stats
        if 'processing_stats' in performance_result.category_stats:
            result.category_stats['processing_stats'] = performance_result.category_stats['processing_stats']

        return result

    def compare_csv_files(self, csv_files: List[str], output_path: Optional[str] = None) -> Dict:
        """Compare multiple CSV files and return comparison results."""
        if len(csv_files) < 2:
            raise ValueError("Need at least 2 CSV files for comparison")

        logger.info(f"Comparing {len(csv_files)} CSV files")

        # Analyze each file
        analyses = []
        for csv_file in csv_files:
            try:
                analysis = self.analyze_csv(csv_file, "full")
                analyses.append(analysis)
            except Exception as e:
                logger.error(f"Failed to analyze {csv_file}: {e}")
                continue

        if len(analyses) < 2:
            raise ValueError("Could not analyze enough files for comparison")

        # Perform comparison
        comparison = self._generate_comparison(analyses)

        # Save if output path provided
        if output_path:
            with open(output_path, 'w') as f:
                json.dump(comparison, f, indent=2)
            logger.info(f"Comparison saved to {output_path}")

        return comparison

    def _generate_comparison(self, analyses: List[AnalysisResult]) -> Dict:
        """Generate comparison between multiple analyses."""
        # Basic comparison info
        comparison = {
            'comparison_timestamp': pd.Timestamp.now().isoformat(),
            'files_compared': [a.filename for a in analyses],
            'number_of_files': len(analyses),

            'summary_comparison': self._compare_summaries(analyses),

            'metric_comparison': self._compare_metrics(analyses),

            'category_comparison': self._compare_categories(analyses),

            'detailed_results': [asdict(a) for a in analyses]
        }

        # Add ranking
        comparison['ranking'] = self._rank_analyses(analyses)

        return comparison

    def _compare_summaries(self, analyses: List[AnalysisResult]) -> Dict:
        """Compare summary metrics across analyses."""
        success_rates = [a.success_rate_percent for a in analyses]
        mean_errors = [a.mean_absolute_error for a in analyses if a.mean_absolute_error is not None]
        processing_times = [a.mean_processing_time_ms for a in analyses]

        return {
            'success_rate_range': {
                'min': min(success_rates),
                'max': max(success_rates),
                'mean': statistics.mean(success_rates)
            },
            'mean_absolute_error_range': {
                'min': min(mean_errors) if mean_errors else None,
                'max': max(mean_errors) if mean_errors else None,
                'mean': statistics.mean(mean_errors) if mean_errors else None
            },
            'processing_time_range': {
                'min': min(processing_times),
                'max': max(processing_times),
                'mean': statistics.mean(processing_times)
            }
        }

    def _compare_metrics(self, analyses: List[AnalysisResult]) -> Dict:
        """Compare detailed metrics across analyses."""
        comparison = {}

        # Compare error metrics
        mae_values = [a.mean_absolute_error for a in analyses if a.mean_absolute_error is not None]
        if mae_values:
            comparison['mean_absolute_error'] = {
                'best': min(mae_values),
                'worst': max(mae_values),
                'spread': max(mae_values) - min(mae_values)
            }

        # Compare success rates
        success_rates = [a.success_rate_percent for a in analyses]
        comparison['success_rate'] = {
            'best': max(success_rates),
            'worst': min(success_rates),
            'spread': max(success_rates) - min(success_rates)
        }

        # Compare processing times
        proc_times = [a.mean_processing_time_ms for a in analyses]
        comparison['processing_time'] = {
            'fastest': min(proc_times),
            'slowest': max(proc_times),
            'spread': max(proc_times) - min(proc_times)
        }

        return comparison

    def _compare_categories(self, analyses: List[AnalysisResult]) -> Dict:
        """Compare category-specific performance across analyses."""
        # Collect all unique categories
        all_categories = set()
        for analysis in analyses:
            all_categories.update(analysis.category_stats.keys())

        # Remove processing_stats if present
        all_categories.discard('processing_stats')

        category_comparison = {}
        for category in all_categories:
            category_comparison[category] = []

            for analysis in analyses:
                if category in analysis.category_stats:
                    cat_stats = analysis.category_stats[category]
                    category_comparison[category].append({
                        'file': analysis.filename,
                        'success_rate': cat_stats.get('success_rate_percent', 0),
                        'mean_error': cat_stats.get('mean_absolute_error'),
                        'processing_time': cat_stats.get('mean_processing_time_ms', 0)
                    })

        return category_comparison

    def _rank_analyses(self, analyses: List[AnalysisResult]) -> List[Dict]:
        """Rank analyses by overall performance."""
        # Define scoring weights
        weights = {
            'success_rate': 0.4,      # Higher is better
            'mean_absolute_error': -0.4,  # Lower is better (negative weight)
            'mean_processing_time': -0.2   # Lower is better (negative weight)
        }

        ranked = []
        for i, analysis in enumerate(analyses):
            score = 0

            # Success rate score (0-100)
            score += analysis.success_rate_percent * weights['success_rate']

            # Error score (lower error = higher score)
            if analysis.mean_absolute_error is not None:
                # Normalize error score (assuming max reasonable error is 1000ml)
                error_score = max(0, (1000 - analysis.mean_absolute_error) / 1000 * 100)
                score += error_score * abs(weights['mean_absolute_error'])

            # Processing time score (lower time = higher score)
            time_score = max(0, (10000 - analysis.mean_processing_time_ms) / 10000 * 100)
            score += time_score * abs(weights['mean_processing_time'])

            ranked.append({
                'rank': i + 1,  # Will be updated after sorting
                'file': analysis.filename,
                'score': score,
                'success_rate': analysis.success_rate_percent,
                'mean_absolute_error': analysis.mean_absolute_error,
                'mean_processing_time_ms': analysis.mean_processing_time_ms
            })

        # Sort by score (highest first)
        ranked.sort(key=lambda x: x['score'], reverse=True)

        # Update ranks
        for i, item in enumerate(ranked):
            item['rank'] = i + 1

        return ranked

    def generate_report(self, analysis: AnalysisResult, output_path: str):
        """Generate a human-readable report from analysis results."""
        report_lines = []

        # Header
        report_lines.append("=" * 80)
        report_lines.append("EVALUATION ANALYSIS REPORT")
        report_lines.append("=" * 80)
        report_lines.append(f"File: {analysis.filename}")
        report_lines.append(f"Generated: {analysis.timestamp}")
        report_lines.append("")

        # Summary statistics
        report_lines.append("SUMMARY STATISTICS")
        report_lines.append("-" * 40)
        report_lines.append(f"Total measurements: {analysis.total_measurements}")
        report_lines.append(f"Successful: {analysis.successful_measurements}")
        report_lines.append(f"Failed: {analysis.failed_measurements}")
        report_lines.append(f"Success rate: {analysis.success_rate_percent".1f"}%")
        report_lines.append("")

        # Error metrics
        if analysis.mean_absolute_error is not None:
            report_lines.append("ERROR METRICS")
            report_lines.append("-" * 40)
            report_lines.append(f"Mean absolute error: {analysis.mean_absolute_error".1f"} ml")
            report_lines.append(f"Median absolute error: {analysis.median_absolute_error".1f"} ml")
            report_lines.append(f"Std dev absolute error: {analysis.std_absolute_error".1f"} ml")
            report_lines.append(f"Root mean square error: {analysis.root_mean_square_error".1f"} ml")
            if analysis.mean_relative_error is not None:
                report_lines.append(f"Mean relative error: {analysis.mean_relative_error".1f"}%")
            report_lines.append("")

        # Performance metrics
        report_lines.append("PERFORMANCE METRICS")
        report_lines.append("-" * 40)
        report_lines.append(f"Mean processing time: {analysis.mean_processing_time_ms".1f"} ms")
        report_lines.append(f"Total processing time: {analysis.total_processing_time_ms".1f"} ms")
        report_lines.append("")

        # Category breakdown
        if analysis.category_stats:
            report_lines.append("CATEGORY BREAKDOWN")
            report_lines.append("-" * 40)

            for category, stats in analysis.category_stats.items():
                if category == 'processing_stats':
                    continue

                report_lines.append(f"\n{category.upper()}:")
                report_lines.append(f"  Total images: {stats.get('total_images', 0)}")
                report_lines.append(f"  Success rate: {stats.get('success_rate_percent', 0)".1f"}%")
                if stats.get('mean_absolute_error') is not None:
                    report_lines.append(f"  Mean error: {stats.get('mean_absolute_error')".1f"} ml")
                report_lines.append(f"  Mean processing time: {stats.get('mean_processing_time_ms', 0)".1f"} ms")

            report_lines.append("")

        # Processing statistics
        if 'processing_stats' in analysis.category_stats:
            report_lines.append("PROCESSING TIME DISTRIBUTION")
            report_lines.append("-" * 40)
            proc_stats = analysis.category_stats['processing_stats']
            report_lines.append(f"Min time: {proc_stats.get('min_time_ms', 0)".1f"} ms")
            report_lines.append(f"Max time: {proc_stats.get('max_time_ms', 0)".1f"} ms")
            report_lines.append(f"Median time: {proc_stats.get('median_time_ms', 0)".1f"} ms")
            report_lines.append(f"95th percentile: {proc_stats.get('percentile_95_ms', 0)".1f"} ms")
            report_lines.append(f"99th percentile: {proc_stats.get('percentile_99_ms', 0)".1f"} ms")

        # Write report
        with open(output_path, 'w') as f:
            f.write('\n'.join(report_lines))

        logger.info(f"Report generated: {output_path}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='CSV Analysis Tools')

    parser.add_argument('--input', '-i', required=True,
                       help='Input CSV file to analyze')
    parser.add_argument('--analysis', '-a', choices=['basic', 'category', 'performance', 'full'],
                       default='full', help='Type of analysis to perform')
    parser.add_argument('--output', '-o',
                       help='Output file for results (JSON)')
    parser.add_argument('--report',
                       help='Generate human-readable report to this file')
    parser.add_argument('--compare', '-c', nargs='+',
                       help='Compare multiple CSV files')
    parser.add_argument('--comparison-output',
                       help='Output file for comparison results')

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(level=logging.INFO)

    analyzer = CSVAnalyzer()

    try:
        if args.compare:
            # Comparison mode
            comparison = analyzer.compare_csv_files(
                args.compare,
                args.comparison_output
            )
            print(json.dumps(comparison, indent=2))

        else:
            # Single file analysis
            analysis = analyzer.analyze_csv(args.input, args.analysis)

            if args.output:
                with open(args.output, 'w') as f:
                    json.dump(asdict(analysis), f, indent=2)
                print(f"Analysis results saved to {args.output}")

            if args.report:
                analyzer.generate_report(analysis, args.report)

            # Print summary to console
            print(f"\nAnalysis Summary for {analysis.filename}:")
            print(f"  Total measurements: {analysis.total_measurements}")
            print(f"  Success rate: {analysis.success_rate_percent".1f"}%")
            print(f"  Mean absolute error: {analysis.mean_absolute_error".1f"} ml" if analysis.mean_absolute_error else "  Mean absolute error: N/A")
            print(f"  Mean processing time: {analysis.mean_processing_time_ms".1f"} ms")

    except Exception as e:
        logger.error(f"Error during analysis: {e}")
        raise


if __name__ == "__main__":
    main()